version: '3'

services:

  app-node:
    build: 
      context: NodeMySQL
    container_name: node-mysql
    volumes:
      - ./NodeMySQL:/usr/src/application
      - /usr/src/application
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=nodedb
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=pedro
    networks:
      - node-network

networks:
  node-network:
    driver: bridge